### ISSUE TITLE
Math Block Editor Hard to Use

### ISSUE THREAD

**Issue by asherhe** [oguhpereira/Dracula-Typora#4]
Whenever I edit a Math Block, the editor background is white, but some other text elements are also white. See below:

![image](https://user-images.githubusercontent.com/35799436/91242759-17e1a680-e6fd-11ea-871f-37305a559ac3.png)

My suggestion is to make the math block background white, if possible.

Thanks!

**Comment by danielcs88** [comment]
> Whenever I edit a Math Block, the editor background is white, but some other text elements are also white. See below:
> 
> ![image](https://user-images.githubusercontent.com/35799436/91242759-17e1a680-e6fd-11ea-871f-37305a559ac3.png)
> 
> My suggestion is to make the math block background white, if possible.
> 
> Thanks!

If you don't mind *getting your hands dirty*, I found how to fix it. All you have to do is navigate to the themes folder for Typora, for Linux it's `~/.config/Typora/themes/dracula.css` and overwriting file with this

https://gist.github.com/danielcs88/914be6f80cbcd3e600779b7103d7e47d

The issue lies in that, apparently there needs to be a setting set for `--rawblock-edit-panel-bd`. I went ahead and created my own variable for its color.

![](https://i.imgur.com/wNwsBCT.png)

So. much. better.
